// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auto_dj.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const autoDJTrackExists = `-- name: AutoDJTrackExists :one
SELECT EXISTS(SELECT 1 FROM auto_dj_tracks WHERE video_id = $1)
`

func (q *Queries) AutoDJTrackExists(ctx context.Context, videoID string) (bool, error) {
	row := q.db.QueryRow(ctx, autoDJTrackExists, videoID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAutoDJTrackCount = `-- name: GetAutoDJTrackCount :one
SELECT COUNT(*) FROM auto_dj_tracks
`

func (q *Queries) GetAutoDJTrackCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getAutoDJTrackCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRandomAutoDJTrack = `-- name: GetRandomAutoDJTrack :one
SELECT id, video_id, title, artist, duration_sec, file_path
FROM auto_dj_tracks
ORDER BY RANDOM()
LIMIT 1
`

type GetRandomAutoDJTrackRow struct {
	ID          pgtype.UUID `json:"id"`
	VideoID     string      `json:"video_id"`
	Title       string      `json:"title"`
	Artist      pgtype.Text `json:"artist"`
	DurationSec int32       `json:"duration_sec"`
	FilePath    string      `json:"file_path"`
}

func (q *Queries) GetRandomAutoDJTrack(ctx context.Context) (GetRandomAutoDJTrackRow, error) {
	row := q.db.QueryRow(ctx, getRandomAutoDJTrack)
	var i GetRandomAutoDJTrackRow
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Title,
		&i.Artist,
		&i.DurationSec,
		&i.FilePath,
	)
	return i, err
}

const insertAutoDJTrack = `-- name: InsertAutoDJTrack :exec
INSERT INTO auto_dj_tracks (video_id, title, artist, duration_sec, file_path)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (video_id) DO NOTHING
`

type InsertAutoDJTrackParams struct {
	VideoID     string      `json:"video_id"`
	Title       string      `json:"title"`
	Artist      pgtype.Text `json:"artist"`
	DurationSec int32       `json:"duration_sec"`
	FilePath    string      `json:"file_path"`
}

func (q *Queries) InsertAutoDJTrack(ctx context.Context, arg InsertAutoDJTrackParams) error {
	_, err := q.db.Exec(ctx, insertAutoDJTrack,
		arg.VideoID,
		arg.Title,
		arg.Artist,
		arg.DurationSec,
		arg.FilePath,
	)
	return err
}
