// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: history.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearHistory = `-- name: ClearHistory :exec
DELETE FROM play_history
`

func (q *Queries) ClearHistory(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearHistory)
	return err
}

const deleteHistoryEntry = `-- name: DeleteHistoryEntry :exec
DELETE FROM play_history WHERE id = $1
`

func (q *Queries) DeleteHistoryEntry(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteHistoryEntry, id)
	return err
}

const getHistory = `-- name: GetHistory :many
SELECT h.id, h.video_id, h.title, h.artist, h.duration_sec, h.requested_by, h.played_at, h.skipped, u.username as requester_name
FROM play_history h
JOIN users u ON h.requested_by = u.id
ORDER BY h.played_at DESC
LIMIT $1 OFFSET $2
`

type GetHistoryParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetHistoryRow struct {
	ID            pgtype.UUID        `json:"id"`
	VideoID       string             `json:"video_id"`
	Title         string             `json:"title"`
	Artist        pgtype.Text        `json:"artist"`
	DurationSec   int32              `json:"duration_sec"`
	RequestedBy   string             `json:"requested_by"`
	PlayedAt      pgtype.Timestamptz `json:"played_at"`
	Skipped       bool               `json:"skipped"`
	RequesterName string             `json:"requester_name"`
}

func (q *Queries) GetHistory(ctx context.Context, arg GetHistoryParams) ([]GetHistoryRow, error) {
	rows, err := q.db.Query(ctx, getHistory, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHistoryRow
	for rows.Next() {
		var i GetHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Title,
			&i.Artist,
			&i.DurationSec,
			&i.RequestedBy,
			&i.PlayedAt,
			&i.Skipped,
			&i.RequesterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertHistory = `-- name: InsertHistory :exec
INSERT INTO play_history (video_id, title, artist, duration_sec, requested_by, played_at, skipped)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertHistoryParams struct {
	VideoID     string             `json:"video_id"`
	Title       string             `json:"title"`
	Artist      pgtype.Text        `json:"artist"`
	DurationSec int32              `json:"duration_sec"`
	RequestedBy string             `json:"requested_by"`
	PlayedAt    pgtype.Timestamptz `json:"played_at"`
	Skipped     bool               `json:"skipped"`
}

func (q *Queries) InsertHistory(ctx context.Context, arg InsertHistoryParams) error {
	_, err := q.db.Exec(ctx, insertHistory,
		arg.VideoID,
		arg.Title,
		arg.Artist,
		arg.DurationSec,
		arg.RequestedBy,
		arg.PlayedAt,
		arg.Skipped,
	)
	return err
}
