// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminSetting struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AutoDjTrack struct {
	ID          pgtype.UUID        `json:"id"`
	VideoID     string             `json:"video_id"`
	Title       string             `json:"title"`
	Artist      pgtype.Text        `json:"artist"`
	DurationSec int32              `json:"duration_sec"`
	FilePath    string             `json:"file_path"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PlayHistory struct {
	ID          pgtype.UUID        `json:"id"`
	VideoID     string             `json:"video_id"`
	Title       string             `json:"title"`
	Artist      pgtype.Text        `json:"artist"`
	DurationSec int32              `json:"duration_sec"`
	RequestedBy string             `json:"requested_by"`
	PlayedAt    pgtype.Timestamptz `json:"played_at"`
	Skipped     bool               `json:"skipped"`
}

type Queue struct {
	ID           pgtype.UUID        `json:"id"`
	YoutubeUrl   string             `json:"youtube_url"`
	VideoID      string             `json:"video_id"`
	Title        string             `json:"title"`
	Artist       pgtype.Text        `json:"artist"`
	DurationSec  int32              `json:"duration_sec"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	RequestedBy  string             `json:"requested_by"`
	Position     int32              `json:"position"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	AudioStatus  string             `json:"audio_status"`
	AudioPath    pgtype.Text        `json:"audio_path"`
}

type SkipVote struct {
	ID        pgtype.UUID        `json:"id"`
	QueueID   pgtype.UUID        `json:"queue_id"`
	UserID    string             `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        string             `json:"id"`
	Username  string             `json:"username"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserTimeout struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    string             `json:"user_id"`
	IssuedBy  string             `json:"issued_by"`
	Reason    pgtype.Text        `json:"reason"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
