// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type AdminSetting struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

type PlayHistory struct {
	ID          string         `json:"id"`
	VideoID     string         `json:"video_id"`
	Title       string         `json:"title"`
	Artist      sql.NullString `json:"artist"`
	DurationSec int64          `json:"duration_sec"`
	RequestedBy string         `json:"requested_by"`
	PlayedAt    string         `json:"played_at"`
	Skipped     int64          `json:"skipped"`
}

type Queue struct {
	ID           string         `json:"id"`
	YoutubeUrl   string         `json:"youtube_url"`
	VideoID      string         `json:"video_id"`
	Title        string         `json:"title"`
	Artist       sql.NullString `json:"artist"`
	DurationSec  int64          `json:"duration_sec"`
	ThumbnailUrl sql.NullString `json:"thumbnail_url"`
	RequestedBy  string         `json:"requested_by"`
	Position     int64          `json:"position"`
	Status       string         `json:"status"`
	CreatedAt    string         `json:"created_at"`
	AudioStatus  string         `json:"audio_status"`
	AudioPath    sql.NullString `json:"audio_path"`
}

type SkipVote struct {
	ID        string `json:"id"`
	QueueID   string `json:"queue_id"`
	UserID    string `json:"user_id"`
	CreatedAt string `json:"created_at"`
}

type User struct {
	ID        string         `json:"id"`
	Username  string         `json:"username"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	Role      string         `json:"role"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

type UserTimeout struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	IssuedBy  string         `json:"issued_by"`
	Reason    sql.NullString `json:"reason"`
	ExpiresAt string         `json:"expires_at"`
	CreatedAt string         `json:"created_at"`
}
