// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	CastSkipVote(ctx context.Context, arg CastSkipVoteParams) error
	ClearHistory(ctx context.Context) error
	CountPendingAutoDJ(ctx context.Context) (int64, error)
	CountSkipVotes(ctx context.Context, queueID string) (int64, error)
	CountUserPendingTracks(ctx context.Context, requestedBy string) (int64, error)
	CreateTimeout(ctx context.Context, arg CreateTimeoutParams) (UserTimeout, error)
	DeleteHistoryEntry(ctx context.Context, id string) error
	DeletePendingAutoDJ(ctx context.Context) error
	DeleteQueueItem(ctx context.Context, id string) error
	DeleteSkipVotesForTrack(ctx context.Context, queueID string) error
	DeleteTimeout(ctx context.Context, userID string) error
	GetActiveQueueIDs(ctx context.Context) ([]string, error)
	GetActiveTimeout(ctx context.Context, userID string) (UserTimeout, error)
	GetAllSettings(ctx context.Context) ([]AdminSetting, error)
	GetCurrentlyPlaying(ctx context.Context) (GetCurrentlyPlayingRow, error)
	GetHistory(ctx context.Context, arg GetHistoryParams) ([]GetHistoryRow, error)
	GetNextPending(ctx context.Context) (GetNextPendingRow, error)
	GetNextPendingExtraction(ctx context.Context) (GetNextPendingExtractionRow, error)
	GetNextReadyPending(ctx context.Context) (GetNextReadyPendingRow, error)
	GetPendingExtractions(ctx context.Context) ([]GetPendingExtractionsRow, error)
	GetQueue(ctx context.Context) ([]GetQueueRow, error)
	GetQueueItem(ctx context.Context, id string) (Queue, error)
	GetSetting(ctx context.Context, key string) (string, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserRole(ctx context.Context, id string) (string, error)
	HasUserVoted(ctx context.Context, arg HasUserVotedParams) (int64, error)
	InsertHistory(ctx context.Context, arg InsertHistoryParams) error
	InsertQueueItem(ctx context.Context, arg InsertQueueItemParams) (Queue, error)
	IsVideoInQueue(ctx context.Context, videoID string) (int64, error)
	MoveToTop(ctx context.Context, id string) error
	RetractSkipVote(ctx context.Context, arg RetractSkipVoteParams) error
	SetBpm(ctx context.Context, arg SetBpmParams) error
	UpdateAudioStatus(ctx context.Context, arg UpdateAudioStatusParams) error
	UpdateDuration(ctx context.Context, arg UpdateDurationParams) error
	UpdateQueueStatus(ctx context.Context, arg UpdateQueueStatusParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
