// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CastSkipVote(ctx context.Context, arg CastSkipVoteParams) error
	CountSkipVotes(ctx context.Context, queueID pgtype.UUID) (int64, error)
	CountUserPendingTracks(ctx context.Context, requestedBy string) (int64, error)
	CreateTimeout(ctx context.Context, arg CreateTimeoutParams) (UserTimeout, error)
	DeleteQueueItem(ctx context.Context, id pgtype.UUID) error
	DeleteSkipVotesForTrack(ctx context.Context, queueID pgtype.UUID) error
	DeleteTimeout(ctx context.Context, userID string) error
	GetActiveQueueIDs(ctx context.Context) ([]pgtype.UUID, error)
	GetActiveTimeout(ctx context.Context, userID string) (UserTimeout, error)
	GetAllSettings(ctx context.Context) ([]AdminSetting, error)
	GetCurrentlyPlaying(ctx context.Context) (GetCurrentlyPlayingRow, error)
	GetHistory(ctx context.Context, arg GetHistoryParams) ([]GetHistoryRow, error)
	GetNextPending(ctx context.Context) (GetNextPendingRow, error)
	GetNextReadyPending(ctx context.Context) (Queue, error)
	GetPendingExtractions(ctx context.Context) ([]GetPendingExtractionsRow, error)
	GetQueue(ctx context.Context) ([]GetQueueRow, error)
	GetQueueItem(ctx context.Context, id pgtype.UUID) (Queue, error)
	GetSetting(ctx context.Context, key string) (string, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserRole(ctx context.Context, id string) (string, error)
	HasUserVoted(ctx context.Context, arg HasUserVotedParams) (bool, error)
	InsertHistory(ctx context.Context, arg InsertHistoryParams) error
	InsertQueueItem(ctx context.Context, arg InsertQueueItemParams) (Queue, error)
	IsVideoInQueue(ctx context.Context, videoID string) (bool, error)
	MoveToTop(ctx context.Context, id pgtype.UUID) error
	RetractSkipVote(ctx context.Context, arg RetractSkipVoteParams) error
	UpdateAudioStatus(ctx context.Context, arg UpdateAudioStatusParams) error
	UpdateQueueStatus(ctx context.Context, arg UpdateQueueStatusParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
