// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queue.sql

package store

import (
	"context"
	"database/sql"
)

const countPendingAutoDJ = `-- name: CountPendingAutoDJ :one
SELECT COUNT(*) FROM queue WHERE requested_by = 'auto-dj' AND status IN ('pending', 'playing')
`

func (q *Queries) CountPendingAutoDJ(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingAutoDJ)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserPendingTracks = `-- name: CountUserPendingTracks :one
SELECT COUNT(*) FROM queue WHERE requested_by = ? AND status IN ('pending', 'playing')
`

func (q *Queries) CountUserPendingTracks(ctx context.Context, requestedBy string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserPendingTracks, requestedBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePendingAutoDJ = `-- name: DeletePendingAutoDJ :exec
DELETE FROM queue WHERE requested_by = 'auto-dj' AND status = 'pending'
`

func (q *Queries) DeletePendingAutoDJ(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deletePendingAutoDJ)
	return err
}

const deleteQueueItem = `-- name: DeleteQueueItem :exec
DELETE FROM queue WHERE queue.id = ?
`

func (q *Queries) DeleteQueueItem(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteQueueItem, id)
	return err
}

const getActiveQueueIDs = `-- name: GetActiveQueueIDs :many
SELECT id FROM queue WHERE status IN ('pending', 'playing')
`

func (q *Queries) GetActiveQueueIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getActiveQueueIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentlyPlaying = `-- name: GetCurrentlyPlaying :one
SELECT q.id, q.youtube_url, q.video_id, q.title, q.artist, q.duration_sec,
       q.thumbnail_url, q.requested_by, q.position, q.status, q.created_at,
       q.audio_status, q.audio_path,
       u.username as requester_name, u.avatar_url as requester_avatar
FROM queue q
JOIN users u ON q.requested_by = u.id
WHERE q.status = 'playing'
LIMIT 1
`

type GetCurrentlyPlayingRow struct {
	ID              string         `json:"id"`
	YoutubeUrl      string         `json:"youtube_url"`
	VideoID         string         `json:"video_id"`
	Title           string         `json:"title"`
	Artist          sql.NullString `json:"artist"`
	DurationSec     int64          `json:"duration_sec"`
	ThumbnailUrl    sql.NullString `json:"thumbnail_url"`
	RequestedBy     string         `json:"requested_by"`
	Position        int64          `json:"position"`
	Status          string         `json:"status"`
	CreatedAt       string         `json:"created_at"`
	AudioStatus     string         `json:"audio_status"`
	AudioPath       sql.NullString `json:"audio_path"`
	RequesterName   string         `json:"requester_name"`
	RequesterAvatar sql.NullString `json:"requester_avatar"`
}

func (q *Queries) GetCurrentlyPlaying(ctx context.Context) (GetCurrentlyPlayingRow, error) {
	row := q.db.QueryRowContext(ctx, getCurrentlyPlaying)
	var i GetCurrentlyPlayingRow
	err := row.Scan(
		&i.ID,
		&i.YoutubeUrl,
		&i.VideoID,
		&i.Title,
		&i.Artist,
		&i.DurationSec,
		&i.ThumbnailUrl,
		&i.RequestedBy,
		&i.Position,
		&i.Status,
		&i.CreatedAt,
		&i.AudioStatus,
		&i.AudioPath,
		&i.RequesterName,
		&i.RequesterAvatar,
	)
	return i, err
}

const getNextPending = `-- name: GetNextPending :one
SELECT id, youtube_url, video_id, title, artist, duration_sec, thumbnail_url,
       requested_by, position, status, created_at
FROM queue
WHERE status = 'pending'
ORDER BY position ASC
LIMIT 1
`

type GetNextPendingRow struct {
	ID           string         `json:"id"`
	YoutubeUrl   string         `json:"youtube_url"`
	VideoID      string         `json:"video_id"`
	Title        string         `json:"title"`
	Artist       sql.NullString `json:"artist"`
	DurationSec  int64          `json:"duration_sec"`
	ThumbnailUrl sql.NullString `json:"thumbnail_url"`
	RequestedBy  string         `json:"requested_by"`
	Position     int64          `json:"position"`
	Status       string         `json:"status"`
	CreatedAt    string         `json:"created_at"`
}

func (q *Queries) GetNextPending(ctx context.Context) (GetNextPendingRow, error) {
	row := q.db.QueryRowContext(ctx, getNextPending)
	var i GetNextPendingRow
	err := row.Scan(
		&i.ID,
		&i.YoutubeUrl,
		&i.VideoID,
		&i.Title,
		&i.Artist,
		&i.DurationSec,
		&i.ThumbnailUrl,
		&i.RequestedBy,
		&i.Position,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getNextPendingExtraction = `-- name: GetNextPendingExtraction :one
SELECT id, youtube_url, video_id
FROM queue
WHERE status = 'pending' AND audio_status = 'pending'
ORDER BY position ASC
LIMIT 1
`

type GetNextPendingExtractionRow struct {
	ID         string `json:"id"`
	YoutubeUrl string `json:"youtube_url"`
	VideoID    string `json:"video_id"`
}

func (q *Queries) GetNextPendingExtraction(ctx context.Context) (GetNextPendingExtractionRow, error) {
	row := q.db.QueryRowContext(ctx, getNextPendingExtraction)
	var i GetNextPendingExtractionRow
	err := row.Scan(&i.ID, &i.YoutubeUrl, &i.VideoID)
	return i, err
}

const getNextReadyPending = `-- name: GetNextReadyPending :one
SELECT q.id, q.youtube_url, q.video_id, q.title, q.artist, q.duration_sec, q.thumbnail_url,
       q.requested_by, q.position, q.status, q.created_at, q.audio_status, q.audio_path,
       COALESCE(u.username, q.requested_by) AS requester_name,
       u.avatar_url AS requester_avatar
FROM queue q
LEFT JOIN users u ON u.id = q.requested_by
WHERE q.status = 'pending' AND q.audio_status = 'ready'
ORDER BY q.position ASC
LIMIT 1
`

type GetNextReadyPendingRow struct {
	ID              string         `json:"id"`
	YoutubeUrl      string         `json:"youtube_url"`
	VideoID         string         `json:"video_id"`
	Title           string         `json:"title"`
	Artist          sql.NullString `json:"artist"`
	DurationSec     int64          `json:"duration_sec"`
	ThumbnailUrl    sql.NullString `json:"thumbnail_url"`
	RequestedBy     string         `json:"requested_by"`
	Position        int64          `json:"position"`
	Status          string         `json:"status"`
	CreatedAt       string         `json:"created_at"`
	AudioStatus     string         `json:"audio_status"`
	AudioPath       sql.NullString `json:"audio_path"`
	RequesterName   string         `json:"requester_name"`
	RequesterAvatar sql.NullString `json:"requester_avatar"`
}

func (q *Queries) GetNextReadyPending(ctx context.Context) (GetNextReadyPendingRow, error) {
	row := q.db.QueryRowContext(ctx, getNextReadyPending)
	var i GetNextReadyPendingRow
	err := row.Scan(
		&i.ID,
		&i.YoutubeUrl,
		&i.VideoID,
		&i.Title,
		&i.Artist,
		&i.DurationSec,
		&i.ThumbnailUrl,
		&i.RequestedBy,
		&i.Position,
		&i.Status,
		&i.CreatedAt,
		&i.AudioStatus,
		&i.AudioPath,
		&i.RequesterName,
		&i.RequesterAvatar,
	)
	return i, err
}

const getPendingExtractions = `-- name: GetPendingExtractions :many
SELECT id, youtube_url, video_id
FROM queue
WHERE status IN ('pending', 'playing') AND audio_status IN ('pending', 'extracting')
ORDER BY position ASC
`

type GetPendingExtractionsRow struct {
	ID         string `json:"id"`
	YoutubeUrl string `json:"youtube_url"`
	VideoID    string `json:"video_id"`
}

func (q *Queries) GetPendingExtractions(ctx context.Context) ([]GetPendingExtractionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingExtractions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingExtractionsRow
	for rows.Next() {
		var i GetPendingExtractionsRow
		if err := rows.Scan(&i.ID, &i.YoutubeUrl, &i.VideoID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQueue = `-- name: GetQueue :many
SELECT q.id, q.youtube_url, q.video_id, q.title, q.artist, q.duration_sec,
       q.thumbnail_url, q.requested_by, q.position, q.status, q.created_at,
       q.audio_status, q.audio_path,
       u.username as requester_name, u.avatar_url as requester_avatar
FROM queue q
JOIN users u ON q.requested_by = u.id
WHERE q.status IN ('pending', 'playing')
ORDER BY q.position ASC
`

type GetQueueRow struct {
	ID              string         `json:"id"`
	YoutubeUrl      string         `json:"youtube_url"`
	VideoID         string         `json:"video_id"`
	Title           string         `json:"title"`
	Artist          sql.NullString `json:"artist"`
	DurationSec     int64          `json:"duration_sec"`
	ThumbnailUrl    sql.NullString `json:"thumbnail_url"`
	RequestedBy     string         `json:"requested_by"`
	Position        int64          `json:"position"`
	Status          string         `json:"status"`
	CreatedAt       string         `json:"created_at"`
	AudioStatus     string         `json:"audio_status"`
	AudioPath       sql.NullString `json:"audio_path"`
	RequesterName   string         `json:"requester_name"`
	RequesterAvatar sql.NullString `json:"requester_avatar"`
}

func (q *Queries) GetQueue(ctx context.Context) ([]GetQueueRow, error) {
	rows, err := q.db.QueryContext(ctx, getQueue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQueueRow
	for rows.Next() {
		var i GetQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.YoutubeUrl,
			&i.VideoID,
			&i.Title,
			&i.Artist,
			&i.DurationSec,
			&i.ThumbnailUrl,
			&i.RequestedBy,
			&i.Position,
			&i.Status,
			&i.CreatedAt,
			&i.AudioStatus,
			&i.AudioPath,
			&i.RequesterName,
			&i.RequesterAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQueueItem = `-- name: GetQueueItem :one
SELECT id, youtube_url, video_id, title, artist, duration_sec, thumbnail_url,
       requested_by, position, status, created_at, audio_status, audio_path
FROM queue WHERE id = ?
`

func (q *Queries) GetQueueItem(ctx context.Context, id string) (Queue, error) {
	row := q.db.QueryRowContext(ctx, getQueueItem, id)
	var i Queue
	err := row.Scan(
		&i.ID,
		&i.YoutubeUrl,
		&i.VideoID,
		&i.Title,
		&i.Artist,
		&i.DurationSec,
		&i.ThumbnailUrl,
		&i.RequestedBy,
		&i.Position,
		&i.Status,
		&i.CreatedAt,
		&i.AudioStatus,
		&i.AudioPath,
	)
	return i, err
}

const insertQueueItem = `-- name: InsertQueueItem :one
INSERT INTO queue (id, youtube_url, video_id, title, artist, duration_sec, thumbnail_url, requested_by, position, audio_status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, (SELECT COALESCE(MAX(position), 0) + 1 FROM queue), ?)
RETURNING id, youtube_url, video_id, title, artist, duration_sec, thumbnail_url, requested_by, position, status, created_at, audio_status, audio_path
`

type InsertQueueItemParams struct {
	ID           string         `json:"id"`
	YoutubeUrl   string         `json:"youtube_url"`
	VideoID      string         `json:"video_id"`
	Title        string         `json:"title"`
	Artist       sql.NullString `json:"artist"`
	DurationSec  int64          `json:"duration_sec"`
	ThumbnailUrl sql.NullString `json:"thumbnail_url"`
	RequestedBy  string         `json:"requested_by"`
	AudioStatus  string         `json:"audio_status"`
}

func (q *Queries) InsertQueueItem(ctx context.Context, arg InsertQueueItemParams) (Queue, error) {
	row := q.db.QueryRowContext(ctx, insertQueueItem,
		arg.ID,
		arg.YoutubeUrl,
		arg.VideoID,
		arg.Title,
		arg.Artist,
		arg.DurationSec,
		arg.ThumbnailUrl,
		arg.RequestedBy,
		arg.AudioStatus,
	)
	var i Queue
	err := row.Scan(
		&i.ID,
		&i.YoutubeUrl,
		&i.VideoID,
		&i.Title,
		&i.Artist,
		&i.DurationSec,
		&i.ThumbnailUrl,
		&i.RequestedBy,
		&i.Position,
		&i.Status,
		&i.CreatedAt,
		&i.AudioStatus,
		&i.AudioPath,
	)
	return i, err
}

const isVideoInQueue = `-- name: IsVideoInQueue :one
SELECT EXISTS(SELECT 1 FROM queue WHERE video_id = ? AND status IN ('pending', 'playing'))
`

func (q *Queries) IsVideoInQueue(ctx context.Context, videoID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, isVideoInQueue, videoID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const moveToTop = `-- name: MoveToTop :exec
UPDATE queue SET position = (SELECT MIN(position) - 1 FROM queue WHERE status = 'pending')
WHERE queue.id = ?
`

func (q *Queries) MoveToTop(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, moveToTop, id)
	return err
}

const updateAudioStatus = `-- name: UpdateAudioStatus :exec
UPDATE queue SET audio_status = ?, audio_path = ? WHERE id = ?
`

type UpdateAudioStatusParams struct {
	AudioStatus string         `json:"audio_status"`
	AudioPath   sql.NullString `json:"audio_path"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateAudioStatus(ctx context.Context, arg UpdateAudioStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAudioStatus, arg.AudioStatus, arg.AudioPath, arg.ID)
	return err
}

const updateDuration = `-- name: UpdateDuration :exec
UPDATE queue SET duration_sec = ? WHERE id = ?
`

type UpdateDurationParams struct {
	DurationSec int64  `json:"duration_sec"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateDuration(ctx context.Context, arg UpdateDurationParams) error {
	_, err := q.db.ExecContext(ctx, updateDuration, arg.DurationSec, arg.ID)
	return err
}

const updateQueueStatus = `-- name: UpdateQueueStatus :exec
UPDATE queue SET status = ? WHERE queue.id = ?
`

type UpdateQueueStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateQueueStatus(ctx context.Context, arg UpdateQueueStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateQueueStatus, arg.Status, arg.ID)
	return err
}
