// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queue.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserPendingTracks = `-- name: CountUserPendingTracks :one
SELECT COUNT(*) FROM queue WHERE requested_by = $1 AND status IN ('pending', 'playing')
`

func (q *Queries) CountUserPendingTracks(ctx context.Context, requestedBy string) (int64, error) {
	row := q.db.QueryRow(ctx, countUserPendingTracks, requestedBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteQueueItem = `-- name: DeleteQueueItem :exec
DELETE FROM queue WHERE queue.id = $1
`

func (q *Queries) DeleteQueueItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteQueueItem, id)
	return err
}

const getActiveQueueIDs = `-- name: GetActiveQueueIDs :many
SELECT id FROM queue WHERE status IN ('pending', 'playing')
`

func (q *Queries) GetActiveQueueIDs(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getActiveQueueIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentlyPlaying = `-- name: GetCurrentlyPlaying :one
SELECT q.id, q.youtube_url, q.video_id, q.title, q.artist, q.duration_sec,
       q.thumbnail_url, q.requested_by, q.position, q.status, q.created_at,
       q.audio_status, q.audio_path,
       u.username as requester_name, u.avatar_url as requester_avatar
FROM queue q
JOIN users u ON q.requested_by = u.id
WHERE q.status = 'playing'
LIMIT 1
`

type GetCurrentlyPlayingRow struct {
	ID              pgtype.UUID        `json:"id"`
	YoutubeUrl      string             `json:"youtube_url"`
	VideoID         string             `json:"video_id"`
	Title           string             `json:"title"`
	Artist          pgtype.Text        `json:"artist"`
	DurationSec     int32              `json:"duration_sec"`
	ThumbnailUrl    pgtype.Text        `json:"thumbnail_url"`
	RequestedBy     string             `json:"requested_by"`
	Position        int32              `json:"position"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	AudioStatus     string             `json:"audio_status"`
	AudioPath       pgtype.Text        `json:"audio_path"`
	RequesterName   string             `json:"requester_name"`
	RequesterAvatar pgtype.Text        `json:"requester_avatar"`
}

func (q *Queries) GetCurrentlyPlaying(ctx context.Context) (GetCurrentlyPlayingRow, error) {
	row := q.db.QueryRow(ctx, getCurrentlyPlaying)
	var i GetCurrentlyPlayingRow
	err := row.Scan(
		&i.ID,
		&i.YoutubeUrl,
		&i.VideoID,
		&i.Title,
		&i.Artist,
		&i.DurationSec,
		&i.ThumbnailUrl,
		&i.RequestedBy,
		&i.Position,
		&i.Status,
		&i.CreatedAt,
		&i.AudioStatus,
		&i.AudioPath,
		&i.RequesterName,
		&i.RequesterAvatar,
	)
	return i, err
}

const getNextPending = `-- name: GetNextPending :one
SELECT id, youtube_url, video_id, title, artist, duration_sec, thumbnail_url,
       requested_by, position, status, created_at
FROM queue
WHERE status = 'pending'
ORDER BY position ASC
LIMIT 1
`

type GetNextPendingRow struct {
	ID           pgtype.UUID        `json:"id"`
	YoutubeUrl   string             `json:"youtube_url"`
	VideoID      string             `json:"video_id"`
	Title        string             `json:"title"`
	Artist       pgtype.Text        `json:"artist"`
	DurationSec  int32              `json:"duration_sec"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	RequestedBy  string             `json:"requested_by"`
	Position     int32              `json:"position"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetNextPending(ctx context.Context) (GetNextPendingRow, error) {
	row := q.db.QueryRow(ctx, getNextPending)
	var i GetNextPendingRow
	err := row.Scan(
		&i.ID,
		&i.YoutubeUrl,
		&i.VideoID,
		&i.Title,
		&i.Artist,
		&i.DurationSec,
		&i.ThumbnailUrl,
		&i.RequestedBy,
		&i.Position,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getNextReadyPending = `-- name: GetNextReadyPending :one
SELECT id, youtube_url, video_id, title, artist, duration_sec, thumbnail_url,
       requested_by, position, status, created_at, audio_status, audio_path
FROM queue
WHERE status = 'pending' AND audio_status = 'ready'
ORDER BY position ASC
LIMIT 1
`

func (q *Queries) GetNextReadyPending(ctx context.Context) (Queue, error) {
	row := q.db.QueryRow(ctx, getNextReadyPending)
	var i Queue
	err := row.Scan(
		&i.ID,
		&i.YoutubeUrl,
		&i.VideoID,
		&i.Title,
		&i.Artist,
		&i.DurationSec,
		&i.ThumbnailUrl,
		&i.RequestedBy,
		&i.Position,
		&i.Status,
		&i.CreatedAt,
		&i.AudioStatus,
		&i.AudioPath,
	)
	return i, err
}

const getPendingExtractions = `-- name: GetPendingExtractions :many
SELECT id, youtube_url, video_id
FROM queue
WHERE status IN ('pending', 'playing') AND audio_status IN ('pending', 'extracting')
ORDER BY position ASC
`

type GetPendingExtractionsRow struct {
	ID         pgtype.UUID `json:"id"`
	YoutubeUrl string      `json:"youtube_url"`
	VideoID    string      `json:"video_id"`
}

func (q *Queries) GetPendingExtractions(ctx context.Context) ([]GetPendingExtractionsRow, error) {
	rows, err := q.db.Query(ctx, getPendingExtractions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingExtractionsRow
	for rows.Next() {
		var i GetPendingExtractionsRow
		if err := rows.Scan(&i.ID, &i.YoutubeUrl, &i.VideoID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQueue = `-- name: GetQueue :many
SELECT q.id, q.youtube_url, q.video_id, q.title, q.artist, q.duration_sec,
       q.thumbnail_url, q.requested_by, q.position, q.status, q.created_at,
       q.audio_status, q.audio_path,
       u.username as requester_name, u.avatar_url as requester_avatar
FROM queue q
JOIN users u ON q.requested_by = u.id
WHERE q.status IN ('pending', 'playing')
ORDER BY q.position ASC
`

type GetQueueRow struct {
	ID              pgtype.UUID        `json:"id"`
	YoutubeUrl      string             `json:"youtube_url"`
	VideoID         string             `json:"video_id"`
	Title           string             `json:"title"`
	Artist          pgtype.Text        `json:"artist"`
	DurationSec     int32              `json:"duration_sec"`
	ThumbnailUrl    pgtype.Text        `json:"thumbnail_url"`
	RequestedBy     string             `json:"requested_by"`
	Position        int32              `json:"position"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	AudioStatus     string             `json:"audio_status"`
	AudioPath       pgtype.Text        `json:"audio_path"`
	RequesterName   string             `json:"requester_name"`
	RequesterAvatar pgtype.Text        `json:"requester_avatar"`
}

func (q *Queries) GetQueue(ctx context.Context) ([]GetQueueRow, error) {
	rows, err := q.db.Query(ctx, getQueue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQueueRow
	for rows.Next() {
		var i GetQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.YoutubeUrl,
			&i.VideoID,
			&i.Title,
			&i.Artist,
			&i.DurationSec,
			&i.ThumbnailUrl,
			&i.RequestedBy,
			&i.Position,
			&i.Status,
			&i.CreatedAt,
			&i.AudioStatus,
			&i.AudioPath,
			&i.RequesterName,
			&i.RequesterAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQueueItem = `-- name: GetQueueItem :one
SELECT id, youtube_url, video_id, title, artist, duration_sec, thumbnail_url,
       requested_by, position, status, created_at, audio_status, audio_path
FROM queue WHERE id = $1
`

func (q *Queries) GetQueueItem(ctx context.Context, id pgtype.UUID) (Queue, error) {
	row := q.db.QueryRow(ctx, getQueueItem, id)
	var i Queue
	err := row.Scan(
		&i.ID,
		&i.YoutubeUrl,
		&i.VideoID,
		&i.Title,
		&i.Artist,
		&i.DurationSec,
		&i.ThumbnailUrl,
		&i.RequestedBy,
		&i.Position,
		&i.Status,
		&i.CreatedAt,
		&i.AudioStatus,
		&i.AudioPath,
	)
	return i, err
}

const insertQueueItem = `-- name: InsertQueueItem :one
INSERT INTO queue (youtube_url, video_id, title, artist, duration_sec, thumbnail_url, requested_by, position, audio_status)
VALUES ($1, $2, $3, $4, $5, $6, $7, (SELECT COALESCE(MAX(position), 0) + 1 FROM queue WHERE status IN ('pending', 'playing')), $8)
RETURNING id, youtube_url, video_id, title, artist, duration_sec, thumbnail_url, requested_by, position, status, created_at, audio_status, audio_path
`

type InsertQueueItemParams struct {
	YoutubeUrl   string      `json:"youtube_url"`
	VideoID      string      `json:"video_id"`
	Title        string      `json:"title"`
	Artist       pgtype.Text `json:"artist"`
	DurationSec  int32       `json:"duration_sec"`
	ThumbnailUrl pgtype.Text `json:"thumbnail_url"`
	RequestedBy  string      `json:"requested_by"`
	AudioStatus  string      `json:"audio_status"`
}

func (q *Queries) InsertQueueItem(ctx context.Context, arg InsertQueueItemParams) (Queue, error) {
	row := q.db.QueryRow(ctx, insertQueueItem,
		arg.YoutubeUrl,
		arg.VideoID,
		arg.Title,
		arg.Artist,
		arg.DurationSec,
		arg.ThumbnailUrl,
		arg.RequestedBy,
		arg.AudioStatus,
	)
	var i Queue
	err := row.Scan(
		&i.ID,
		&i.YoutubeUrl,
		&i.VideoID,
		&i.Title,
		&i.Artist,
		&i.DurationSec,
		&i.ThumbnailUrl,
		&i.RequestedBy,
		&i.Position,
		&i.Status,
		&i.CreatedAt,
		&i.AudioStatus,
		&i.AudioPath,
	)
	return i, err
}

const isVideoInQueue = `-- name: IsVideoInQueue :one
SELECT EXISTS(SELECT 1 FROM queue WHERE video_id = $1 AND status IN ('pending', 'playing'))
`

func (q *Queries) IsVideoInQueue(ctx context.Context, videoID string) (bool, error) {
	row := q.db.QueryRow(ctx, isVideoInQueue, videoID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const moveToTop = `-- name: MoveToTop :exec
UPDATE queue SET position = (SELECT MIN(position) - 1 FROM queue WHERE queue.status = 'pending')
WHERE queue.id = $1
`

func (q *Queries) MoveToTop(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, moveToTop, id)
	return err
}

const updateAudioStatus = `-- name: UpdateAudioStatus :exec
UPDATE queue SET audio_status = $2, audio_path = $3 WHERE queue.id = $1
`

type UpdateAudioStatusParams struct {
	ID          pgtype.UUID `json:"id"`
	AudioStatus string      `json:"audio_status"`
	AudioPath   pgtype.Text `json:"audio_path"`
}

func (q *Queries) UpdateAudioStatus(ctx context.Context, arg UpdateAudioStatusParams) error {
	_, err := q.db.Exec(ctx, updateAudioStatus, arg.ID, arg.AudioStatus, arg.AudioPath)
	return err
}

const updateQueueStatus = `-- name: UpdateQueueStatus :exec
UPDATE queue SET status = $2 WHERE queue.id = $1
`

type UpdateQueueStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateQueueStatus(ctx context.Context, arg UpdateQueueStatusParams) error {
	_, err := q.db.Exec(ctx, updateQueueStatus, arg.ID, arg.Status)
	return err
}
