// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package store

import (
	"context"
)

const getAllSettings = `-- name: GetAllSettings :many
SELECT key, value, updated_at FROM admin_settings
`

func (q *Queries) GetAllSettings(ctx context.Context) ([]AdminSetting, error) {
	rows, err := q.db.Query(ctx, getAllSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminSetting
	for rows.Next() {
		var i AdminSetting
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM admin_settings WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO admin_settings (key, value, updated_at) VALUES ($1, $2, now())
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now()
`

type UpsertSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSetting, arg.Key, arg.Value)
	return err
}
