// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: timeouts.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTimeout = `-- name: CreateTimeout :one
INSERT INTO user_timeouts (user_id, issued_by, reason, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, issued_by, reason, expires_at, created_at
`

type CreateTimeoutParams struct {
	UserID    string             `json:"user_id"`
	IssuedBy  string             `json:"issued_by"`
	Reason    pgtype.Text        `json:"reason"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateTimeout(ctx context.Context, arg CreateTimeoutParams) (UserTimeout, error) {
	row := q.db.QueryRow(ctx, createTimeout,
		arg.UserID,
		arg.IssuedBy,
		arg.Reason,
		arg.ExpiresAt,
	)
	var i UserTimeout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IssuedBy,
		&i.Reason,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTimeout = `-- name: DeleteTimeout :exec
DELETE FROM user_timeouts WHERE user_id = $1 AND expires_at > now()
`

func (q *Queries) DeleteTimeout(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteTimeout, userID)
	return err
}

const getActiveTimeout = `-- name: GetActiveTimeout :one
SELECT id, user_id, issued_by, reason, expires_at, created_at FROM user_timeouts
WHERE user_id = $1 AND expires_at > now()
ORDER BY expires_at DESC
LIMIT 1
`

func (q *Queries) GetActiveTimeout(ctx context.Context, userID string) (UserTimeout, error) {
	row := q.db.QueryRow(ctx, getActiveTimeout, userID)
	var i UserTimeout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IssuedBy,
		&i.Reason,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
